### ISSUE TITLE
Overload which file how?

### ISSUE THREAD

**Issue by lief-erickson** [jekyll-one/j1-template-starter#2]
In `home.yml` ([L151-L153](https://github.com/jekyll-one/j1-template-starter/blob/main/_data/layouts/home.yml#L151-L153)) there's a hint to NOT edit the template files but suggests there's another way to do so. Unfortunately, the URL for how appears to be a To Do item.

@j1juergen, how is one supposed to overload the J1 templates?

**Comment by jekyll-one** [comment]
With the latest version of the J1 GEM  2022.4.4, I changed the comments of all layout-related files. Some comments in older versions were confusing, outdated, or are not valid anymore.

In general, the J1 Template should be configured, not modified. Code changes (for the GEM version) of the code base are not recommended. This is different in comparison to other templates available for Jekyll. Most other templates are scaffolds/skeletons that are needed to be modified for individual usage. If you plan to modify the GEM version of J1 (runtime version), add/create your files (e.g., a new type of layout) rather than changing the existing code base. This ensures that your website will continue to work for newer versions of the J1 Template GEM.

From your questions, I assume you intend to modify the code. As mentioned, create and add your code to not conflict with the existing code base. The layout system used by Jekyll is not easy to understand. 1 put much more complexity on top to make J1 fully configurable. Work in this area requires a good knowledge of programming techniques for HTML, CSS, Javascript, Liquid, Jekyll, and Ruby, as well as using XML and Yaml. Again, consider what you're doing if you modify the Template.

If your term of overloading means adding and injecting your (custom) code for layouts, it is quite simple to manage. Please check the layout config home.yml of the latest version v2022.4.4 of the GEM. The(new) comments explain where to place custom code and how to inject it.

Finally, a better solution to customize J1 may be creating your template GEM. The J1 development system (development version) is available at Github: https://github.com/jekyll-one-org/j1-template.
